apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-log-reader
  labels:
    app: python-log-reader
  namespace: python-log-reader-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-log-reader
  template:
    metadata:
      labels:
        app: python-log-reader
    spec:
      containers:
      - name: python-log-reader
        image: docker.io/meghe/python-log-reader:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
