apiVersion: v1
kind: Service
metadata:
  name: python-log-reader
  labels:
    app: python-log-reader
spec:
  selector:
    app: python-log-reader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
